version: "3.9"

services:
  app-ascetic-ddd-go:
    build:
      context: .
    image: ascetic-ddd-go
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: app-ascetic-ddd-go
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - ascetic-ddd-go
    entrypoint: /bin/sh

  db-ascetic-ddd-go:
    container_name: db-ascetic-ddd-go
    image: postgres:15.3
    working_dir: /app
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "${DB_PG_DATA}"
    volumes:
      - ./:/app
      - ./docker-compose/postgresql/master/:/docker-entrypoint-initdb.d
      - ./docker-compose/postgresql/master/ascetic-ddd-go.conf:/etc/postgresql/postgresql.conf
      - ./db_data/master:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ascetic-ddd-go

  pgadmin-ascetic-ddd-go:
    container_name: pgadmin-ascetic-ddd-go
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "${PGADMIN_CONFIG_SERVER_MODE}"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5052:80"
    restart: unless-stopped
    networks:
      - ascetic-ddd-go

  vault-ascetic-ddd-go:
    container_name: vault-ascetic-ddd-go
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test-root-token
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: test-root-token
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: >
      sh -c "
        vault server -dev -dev-root-token-id=test-root-token -dev-listen-address=0.0.0.0:8200 &
        sleep 2 &&
        vault secrets enable transit &&
        wait
      "
    restart: unless-stopped
    networks:
      - ascetic-ddd-go

networks:
  ascetic-ddd-go:
      driver: bridge
